import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {Header, Footer} from "@/components/index";


// Good UI fonts:
// Inter (best for dashboards)
// Poppins (modern UI)
// Roboto (clean)
// Open Sans (simple)
const inter = Inter({ subsets: ["latin"], display: "swap" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { ToastProvider } from "@/context/ToastContext";
import { AuthProvider } from "@/context/AuthContext";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.className} h-full antialiased`}>
      <body suppressHydrationWarning className="min-h-full flex flex-col">
        <ToastProvider>
          <AuthProvider>
            <Header />
            <main className="flex-1 bg-white text-black">{children}</main>
            <Footer />
          </AuthProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
